#!/usr/bin/env python3
"""Rebuild the public COURSE_MAP.md from the student course catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


EXPECTED_REPO = "python-machine-learning-2026-student"
ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "docs" / "assets" / "course-catalog.json"
COURSE_MAP_PATH = ROOT / "COURSE_MAP.md"


def assert_student_repo() -> None:
    """Refuse to write unless this is the expected public student repository."""
    if ROOT.name != EXPECTED_REPO or not (ROOT / ".git").exists():
        raise SystemExit(f"Refusing to write outside {EXPECTED_REPO}")

    root = ROOT.resolve()
    for target in (CATALOG_PATH, COURSE_MAP_PATH):
        if not target.resolve().is_relative_to(root):
            raise SystemExit(f"Output escapes student repository: {target}")


def load_catalog() -> dict:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    repository = catalog.get("repository", {})
    if repository.get("name") != EXPECTED_REPO or repository.get("visibility") != "public":
        raise SystemExit("Catalog repository metadata does not identify the public student repo")
    return catalog


def notebook_links(chapter: dict) -> str:
    return "<br>".join(
        f"[{notebook['label']}]({notebook['colab']})"
        for notebook in chapter["notebooks"]
    )


def course_row(section: dict, chapter: dict) -> str:
    number = int(chapter["number"])
    route = section["route"]
    entry = f"[{section['label']}](docs/{route})"
    handout = f"[Ch{number:02d} PDF](docs/{chapter['handout']})"
    compute = chapter["compute"]
    conditions = f"{compute['runtime']}・{compute['duration']}・{compute['mode']}"
    cells = [
        entry,
        f"Ch{number:02d}",
        chapter["title"],
        handout,
        notebook_links(chapter),
        chapter["outcome"],
        conditions,
    ]
    return "| " + " | ".join(str(cell).replace("|", "／") for cell in cells) + " |"


def render_course_map(catalog: dict) -> str:
    lines = [
        "<!-- Generated by scripts/build_student_course_portal.py; edit docs/assets/course-catalog.json instead. -->",
        "# Course Map・學生公開課程地圖",
        "",
        "五日課程、學生講義與 Colab 的單一資料來源是 [`docs/assets/course-catalog.json`](docs/assets/course-catalog.json)。",
        "",
        "| 公開入口 | 章節 | 主題 | 學生講義 | Colab-ready notebooks | 完成後，你可以 | 執行條件 |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]

    sections = [*catalog["days"], catalog["extension"]]
    for section in sections:
        lines.extend(course_row(section, chapter) for chapter in section["chapters"])

    practicum = catalog["practicum"]
    lines.extend(
        [
            "",
            "## 五日課程壓軸",
            "",
            f"[{practicum['title']}](docs/{practicum['route']})：{practicum['summary']}",
            "",
            "全站教材使用 Google Colab；資料直接在 Notebook 取得，Kaggle 只標示題目出處，無須登入。",
            "",
        ]
    )

    chapter_count = sum(len(section["chapters"]) for section in sections)
    notebook_count = sum(
        len(chapter["notebooks"])
        for section in sections
        for chapter in section["chapters"]
    )
    if chapter_count != catalog["course"]["chapterCount"] or notebook_count != catalog["course"]["notebookCount"]:
        raise SystemExit(
            f"Catalog totals mismatch: {chapter_count} chapters, {notebook_count} notebooks"
        )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when COURSE_MAP.md is out of date")
    args = parser.parse_args()

    assert_student_repo()
    rendered = render_course_map(load_catalog())
    current = COURSE_MAP_PATH.read_text(encoding="utf-8") if COURSE_MAP_PATH.exists() else ""

    if args.check:
        if current != rendered:
            print("COURSE_MAP.md is out of date; run this script without --check")
            return 1
        print("COURSE_MAP.md matches course-catalog.json")
        return 0

    if current == rendered:
        print("COURSE_MAP.md already up to date")
        return 0

    COURSE_MAP_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Updated {COURSE_MAP_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
